### PR TITLE
Linter Added

### PR DESCRIPTION
**Pull request by Daniel-olaO**

### CODE REVIEW

**Comment by Russell-Pollari** [comment]
looks like this branch also has the commit with all of your `__pycache__` folders.. have you fixed that yet? Those should not be in version control

**Comment by Daniel-olaO** [comment]
I have done that on the user branch, that should resolve the issue

**Comment by Russell-Pollari** [comment]
sounds good! Just be sure to merge master into this branch once you merge #4

**Comment by Russell-Pollari** [comment]
Can you either merge master or rebase on master? Some of these changes, I've reviewed already in #4

**Review by Russell-Pollari — CHANGES_REQUESTED** [review]
Sorry Daniel, This PR still has changes that I've reviewed already. Can you just `merge master` ?

**Comment by Daniel-olaO** [comment]
Ok

**Pull request merged**
