### PR TITLE
User athentication methhod added

### PR DESCRIPTION
**Pull request by Daniel-olaO**

### CODE REVIEW

**Review by Russell-Pollari — CHANGES_REQUESTED** [review]
Can you add the `__pycache__` folders to your `.gitignore`? These files should not be committed to version control.

You may also need to do something like `git rm __pycache__ -r --cached` to clear them from version control

**Review by Russell-Pollari — CHANGES_REQUESTED** [review]
Nice! but you still have some __pycache__ folders in your api folder, and in the migrations folder

**Review by Russell-Pollari — CHANGES_REQUESTED** [review]
You do want to commit migrations, you just don't want to commit all the various `__pycache__` folders.

I think your `.gitignore` was fine before, you just still need to remove the other `__pycache__` folders from version control, `git rm <folder> --cached`

**Comment by Daniel-olaO** [comment]
> You do want to commit migrations, you just don't want to commit all the various `__pycache__` folders.
> 
> I think your `.gitignore` was fine before, you just still need to remove the other `__pycache__` folders from version control, `git rm <folder> --cached`

**Pull request closed without merging**
